<?php
// Headers for download
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=bookTransaction.xls");

// Output buffering to capture the output generated by the included file
ob_start();

// Include your bookTransaction.php file
require '../assets/reports/bookTransaction.php';

// Get the captured output
$content = ob_get_clean();

// Output the captured content
echo $content;
?>
